# Base configs
baseurl: "https://jhaderl.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography"
author: "JFH"
header:
 title: "Photography"
 subtitle: "If you want to get into contact with me, use my LinkedIn: https://de.linkedin.com/in/jonas-haderlein-phd-360bb9141"
footer:
 name: "JFH"
