# Base configs
baseurl: "https://jonashaderlein.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography"
author: "JFH"
header:
 title: "Photography"
 subtitle: "by JFH"
footer:
 name: "JFH"
